spring:
  application:
    name: sharing-table
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
#配置数据源
  datasource:
    druid:
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,logback,config  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙'config'用于提示Druid数据源需要对数据库密码进行解密
      filter:
        config:
          enabled: true
data01:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/test01?useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: 123456
data02:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/test02?useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: 123456
face:
  database:
    name01: test01
    name02: test02
    thread_num: 5 #分片线程
